// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3OauSyH1t0ZFSVVHRFy7yUoRMg2Rp2A4',
    appId: '1:350862324854:web:40cceadc57c39ef4ebdb57',
    messagingSenderId: '350862324854',
    projectId: 'my-todolist-flutterfire',
    authDomain: 'my-todolist-flutterfire.firebaseapp.com',
    storageBucket: 'my-todolist-flutterfire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWg5TRzfkpHPiZeXIs8CHZs-j7qX8go10',
    appId: '1:350862324854:android:6192b882d793dd7debdb57',
    messagingSenderId: '350862324854',
    projectId: 'my-todolist-flutterfire',
    storageBucket: 'my-todolist-flutterfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnsetQfnwE0SMKNlk-jcO-QjpbZaUyJ_o',
    appId: '1:350862324854:ios:23e5129da8320031ebdb57',
    messagingSenderId: '350862324854',
    projectId: 'my-todolist-flutterfire',
    storageBucket: 'my-todolist-flutterfire.appspot.com',
    iosBundleId: 'com.example.flutterfireFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnsetQfnwE0SMKNlk-jcO-QjpbZaUyJ_o',
    appId: '1:350862324854:ios:6e811c69034116e9ebdb57',
    messagingSenderId: '350862324854',
    projectId: 'my-todolist-flutterfire',
    storageBucket: 'my-todolist-flutterfire.appspot.com',
    iosBundleId: 'com.example.flutterfireFirstApp.RunnerTests',
  );
}
